name: Build Windows EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build EXE
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pywin32 pyinstaller

      - name: Compile to EXE
        run: |
          pyinstaller --onefile --windowed --name "Shutdown_Prompt" main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Shutdown_Prompt
          path: dist/Shutdown_Prompt.exe
