name: Build Windows EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build EXE
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pywin32 pyinstaller Pillow

      - name: Compile to EXE using spec file
        run: |
          pyinstaller -i logo.ico main_v2.py

      - name: Create zip package
        run: |
          Compress-Archive -Path dist\ShutdownPrompt.exe -DestinationPath dist\ShutdownPrompt.zip
        shell: pwsh

      - name: Upload zip package
        uses: actions/upload-artifact@v4
        with:
          name: ShutdownPrompt
          path: dist\ShutdownPrompt.zip
